apiVersion: v1
kind: Namespace
metadata:
  name: astro-pipeline
  labels:
    name: astro-pipeline
    project: astronomical-data-pipeline
    environment: production
  annotations:
    description: "Astronomical data processing pipeline namespace"
    contact: "stsci-demo@example.com"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: astro-pipeline-quota
  namespace: astro-pipeline
spec:
  hard:
    requests.cpu: "50"
    requests.memory: 100Gi
    limits.cpu: "100"
    limits.memory: 200Gi
    persistentvolumeclaims: "10"
    services: "20"
    secrets: "20"
    configmaps: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: astro-pipeline-limits
  namespace: astro-pipeline
spec:
  limits:
  - default:
      memory: "2Gi"
      cpu: "1000m"
    defaultRequest:
      memory: "512Mi"
      cpu: "100m"
    type: Container
  - max:
      memory: "8Gi"
      cpu: "4000m"
    min:
      memory: "128Mi"
      cpu: "50m"
    type: Container